# These are supported funding model platforms

# Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
github: [ EDBCREPO ] 

# Replace with a single Ko-fi username
ko_fi: https://ko-fi.com/edbc_repo

# Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
custom: [ 'paypal.me/EDBCREPO' ]

lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
open_collective: # Replace with a single Open Collective username
buy_me_a_coffee: # Replace with a single Buy Me a Coffee username
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
patreon: # Replace with a single Patreon username
polar: # Replace with a single Polar username
